# Generated by Django 5.0.4 on 2024-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_collection_product_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_slug',
            field=models.SlugField(default='a', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
