# Generated by Django 5.0.4 on 2024-05-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
        ('store', '0005_collection_collection_slug'),
    ]

    operations = [
    ]
