# Generated by Django 5.0.4 on 2024-05-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(related_name='product_collections', to='store.collection'),
        ),
    ]
