# Generated by Django 5.0.4 on 2024-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
