# Generated by Django 5.0.4 on 2024-05-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20240506_1442'),
        ('store', '0010_product_view_count'),
    ]

    operations = [
    ]
