# Generated by Django 5.0.4 on 2024-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='large_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
