# Generated by Django 5.0.4 on 2024-05-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_collections'),
        ('store', '0014_remove_product_large_image_alter_product_image'),
    ]

    operations = [
    ]
