# Generated by Django 5.0.4 on 2024-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_merge_20240508_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
